version: '3.4'

services:
  app:
    container_name: ares
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - .:/opt/app/api
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  redis:
    container_name: redis-cache
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --logLevel warning --requirepass tcdev
    ports:
      - '6379:6379'
    volumes:
      - redis-cache:/data

volumes:
  redis-cache:
    driver: local
  data: